apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &app_name app
  labels:
    application: patroni
    cluster-name: *app_name
spec:
  replicas: 1
  serviceName: *app_name
  selector:
    matchLabels:
      application: app
      cluster-name: *app_name
  template:
    metadata:
      labels:
        application: app
        cluster-name: *app_name
    spec:
      containers:
      - name: *app_name
        image: $IMAGE
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        ports:
        - containerPort: 8001
          protocol: TCP